travis:
  secure:
    BINSTAR_TOKEN: Rj1a13RGYveu9QLErVHcvfW8bLZrfAh+wNUE7TFslNY5v9lOS1tNkR0O1HQ/XzkZmjpTrc0PNskpcWwn+zzLr6i8TysdNbzodjQw7KZ6L3GEQ3KY5iF5rHwb7cP5LgKL8p4LNeE6g5SBkYdhYTXLKzp9I0nY0TUENmQMstMcu3ig1lClDsbBJgOAaS6wp9J9LmejpG8wzYbFddf8rYLQRPbzGcdVctF8Io4y4uIdhjnYdAY5GUCmDOgfLzI5W6lDMfX6txzskUsABCPh6fiv4Ks2d87LNY8B0JcVnO63YObfzkd4cuxYevjK6Tqf2UAwuSjB0r3xJIPBXH96gTJ48+naBKN8CTr8SBaWSvyCzl1ylphOedySIniHVSwDXSBTTenvMiqWoB4xeTtZJIztyvIXtrcaaCr/o9CBPpPDoXJ943ODlCH13uD1AAcRaxWANc/OuD6SRYkEhjtNqqgJ+ZfdpuXhOQGC6aDVftfqbja6wO243ZsEThxVrrDg+rwk62DzA1v6prsY/JjapZflVOIA1DEzo3+Rbq8eX1qdawdBVK9p3hlhSPkzrrjC1HQpMfnQjbstlFEgajm48y/S4oJsmpZwhXeZRxVlmcNiG9qjIL9PX1vElTQ6oYs/StKUclctm1dUKUqiYg//23JGxnpHjrt19l1p1NLxD0B9IBY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
